[project]
name = 'pancax'
version = '0.0.5'
authors = [
  {name = 'Craig M. Hamel, email = <chamel@sandia.gov>'}
]
dependencies = [
  'matplotlib',
  'netCDF4',
  'pandas',
  'scipy',
  'vtk'
]

[project.optional-dependencies]
cpu = [
  'chex',
  'equinox',
  'jax==0.4.33',
  'jaxtyping',
  'optax'
]
cuda = [
  'chex',
  'equinox',
  'jax[cuda12]==0.4.33',
  'jaxtyping',
  'optax'
]
docs = [
  'sphinx',
  'sphinx-copybutton',
  'sphinx-rtd-theme',
  'sphinxcontrib-bibtex',
  'sphinxcontrib-napoleon'
]
test = [
  'pytest',
  'pytest-cov',
]
viz = [
  'pyvista'
]

[tool.setuptools]
packages = [
  'pancax',
  'pancax.bcs',
  'pancax.bvps',
  'pancax.constitutive_models',
  'pancax.data',
  'pancax.domains',
  'pancax.fem',
  'pancax.fem.elements',
  'pancax.kernels',
  'pancax.loss_functions',
  'pancax.math',
  'pancax.networks',
  'pancax.optimizers',
  'pancax.physics_kernels',
  'pancax.problems'
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no coverage",
  "if __name__ == '__main__'",
  "def main",
  "def __repr__",
  "pass"
]
