name: Deploy
on:
  push:
    branches: main

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          os:
          - ubuntu-latest
          python-version:
          # - '3.10'
          # - '3.11'
          - '3.12'
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install build deps
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools twine wheel
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.python-version }}-wheel
        path: target/wheels
