name: Documentation

on:
  pull_request:
    branches: main
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    # container: mrbuche/exodus
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install .[cpu,docs]
        cd docs
        sphinx-apidoc -o source/ ../pancax -P
        make html
    - name: Deploy
      usese: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
        force_orphan: true
